### ISSUE TITLE
sun.security.pkcs11.wrapper.PKCS11Exception

### ISSUE THREAD

**Issue by muratgokhanolgunoz** [ahmetaltay33/esign#6]
Merhaba;
Projenizi test etmek istediğimde

Oca 17, 2024 5:16:46 ÖS tr.gov.tubitak.uekae.esya.api.xmlsignature.formats.BaseSignatureFormat debugSign
FINE: key : class tr.gov.tubitak.uekae.esya.api.smartcard.util.APDUSigner
Exception in thread "main" java.lang.IllegalAccessError: class tr.gov.tubitak.uekae.esya.api.smartcard.apdu.APDUSmartCard (in unnamed module @0x290222c1) cannot access class sun.security.pkcs11.wrapper.PKCS11Exception (in module jdk.crypto.cryptoki) because module jdk.crypto.cryptoki does not export sun.security.pkcs11.wrapper to unnamed module @0x290222c1
	at tr.gov.tubitak.uekae.esya.api.smartcard.apdu.APDUSmartCard.sign(APDUSmartCard.java)
	at tr.gov.tubitak.uekae.esya.api.smartcard.util.APDUSigner.sign(APDUSigner.java)
	at tr.gov.tubitak.uekae.esya.api.xmlsignature.formats.BaseSignatureFormat.sign(BaseSignatureFormat.java)
	at tr.gov.tubitak.uekae.esya.api.xmlsignature.formats.BES.sign(BES.java)
	at tr.gov.tubitak.uekae.esya.api.xmlsignature.XMLSignature.sign(XMLSignature.java)
	at tr.com.ahmetaltay.esign.XmlSigner.signBes(XmlSigner.java:52)
	at tr.com.ahmetaltay.esign.App.main(App.java:112)

bu şekilde bir exception dönüyor. Biraz araştırdığımda olası birkaç çözüm yolu denedim fakat maalesef başarılı olmadı. Benzer bir proje üzerinde çalışıyorum ve aynı hatayı bu projede de alınca yazmak istedim. Şuan target java 17. Bu hata ve çözümü ile ilgili bilginiz var mı ? 

Yardımlarınızı rica ederim. İyi çalışmalar.

**Comment by ahmetaltay33** [comment]
Esya api Java 8 ile uyumlu pkcs11 lib bulunamamış. Bu yüzden olabilir hata

**Comment by muratgokhanolgunoz** [comment]
Java versiyonu 8 olarak değiştirdim. Bunun haricinde hata farklı bir yer ile bağlantılı olarak çıktı sonradan farkettim. Bilgi için teşekkür ederim. İyi çalışmalar dilerim.
